### ISSUE TITLE
System Stop command deployed new instances

### ISSUE THREAD

**Issue by darahayes** [nearform/nscale#89]
While working with the autoscaling version of the SUDC system I went through the following steps:
- Deployed the system. This was successful. 2 machines went up and `system check` was returning no problems.
- I set up some very trivial triggers based on average network in on the `nscale-scaling-down` and `nscale-scaling-up` policies.
- Used apache benchmark to simulate a few thousand requests from a couple of hundred users.
- New machines spun up and after some time they were torn down.
- Once the number of instances went back to the MinSize of 2 I manually deleted the ASG, the launch configuration, the ELB, SG, and terminated the Instances.
- Ran `system stop sudc autoscaling`

And here was the following output:

``` bash
ubuntu@ip-172-30-0-46:~/sudc-system$ nscale system stop sudc autoscaling
--> deploying...
--> deploying plan...
add awsWebElb-3ab215e9 aws-elb
start awsWebElb-3ab215e9 aws-elb
starting
add awsWebSg-33b7ef74 aws-sg
start awsWebSg-33b7ef74 aws-sg
add awsAutoscaling-b34fa4a6 aws-autoscaling
start awsAutoscaling-b34fa4a6 aws-autoscaling
not ok!
ERROR: Server disconnected abruptly. 
```

Some sort of deployment occurred before crashing. In the AWS console two new instances were in the process of spinning up. The logs showed the following:

``` bash
ubuntu@ip-172-30-0-46:~/sudc-system$ nscale log
                  "CidrIp": "0.0.0.0/0"
                }
              ]
            }
          ],
          "IpPermissionsEgress": [
            {
              "IpProtocol": "-1",
              "UserIdGroupPairs": [],
              "IpRanges": [
                {
                  "CidrIp": "0.0.0.0/0"
                }
              ]
            }
          ]
        }
      },
      "awsAutoscaling-b34fa4a6": {
        "id": "awsAutoscaling-b34fa4a6",
        "containedBy": "awsWebSg-33b7ef74",
        "containerDefinitionId": "awsAutoscaling",
        "type": "aws-autoscaling",
        "contains": [
          "awsAMachine-40dbfb4d"
        ],
        "specific": {
          "ImageId": "ami-4b90b27b",
          "MinSize": 2,
          "MaxSize": 5
        }
      },
      "awsAMachine-40dbfb4d": {
        "id": "awsAMachine-40dbfb4d",
        "containedBy": "awsAutoscaling-b34fa4a6",
        "containerDefinitionId": "awsAMachine",
        "type": "blank-container",
        "contains": [],
        "specific": {}
      }
    },
    "name": "autoscaling"
  },
  "repoPath": "/home/ubuntu/sudc-system"
}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"creating deployment plan","time":"2015-05-14T16:06:51.455Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"deploying plan","time":"2015-05-14T16:06:51.604Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: add","time":"2015-05-14T16:06:51.604Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: start","time":"2015-05-14T16:06:52.108Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-elb","level":30,"msg":"starting","time":"2015-05-14T16:06:52.120Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"stdout: starting","time":"2015-05-14T16:06:52.121Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: add","time":"2015-05-14T16:06:52.121Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: start","time":"2015-05-14T16:06:52.541Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: add","time":"2015-05-14T16:06:52.554Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"calling: start","time":"2015-05-14T16:06:52.566Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"LaunchConfigurationNames":["lc-sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeLaunchConfigurations","time":"2015-05-14T16:06:52.598Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"msg":"createLaunchConfiguration { LaunchConfigurationName: 'lc-sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b',\n  AssociatePublicIpAddress: true,\n  ImageId: 'ami-4b90b27b',\n  InstanceType: 't2.small',\n  SecurityGroups: [ 'sg-1e8d917b' ],\n  KeyName: 'dhayes-nscale' }","time":"2015-05-14T16:06:52.637Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"LaunchConfigurationNames":["lc-sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeLaunchConfigurations","time":"2015-05-14T16:06:52.775Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"loadBalancerName":"awsWebElb-3ab215e9","msg":"LoadBalancerName","time":"2015-05-14T16:06:52.831Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:06:52.831Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","MaxSize":5,"MinSize":2,"HealthCheckGracePeriod":600,"HealthCheckType":"ELB","LaunchConfigurationName":"lc-sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","LoadBalancerNames":["awsWebElb-3ab215e9"],"VPCZoneIdentifier":"subnet-838e7ef4","Tags":[{"Key":"Name","PropagateAtLaunch":true,"Value":"awsAutoscaling-b34fa4a6"},{"Key":"nscale-id","PropagateAtLaunch":false,"Value":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6"},{"Key":"nscale-system","PropagateAtLaunch":true,"Value":"sudc-system-autoscaling"}],"msg":"createAutoScalingGroup","time":"2015-05-14T16:06:52.874Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:06:53.297Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:06:53.885Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":0,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:06:53.944Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:06:59.947Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":1,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:00.010Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:07:06.017Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":2,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:06.073Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:07:12.080Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":3,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:12.140Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:07:18.142Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":4,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:18.198Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:07:24.204Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":5,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:24.261Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"AutoScalingGroupNames":["sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b"],"MaxRecords":1,"msg":"describeAutoScalingGroups","time":"2015-05-14T16:07:30.266Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"module":"aws-autoscaling","level":30,"groupName":"sudc-system-autoscaling-awsAutoscaling-b34fa4a6-ami-4b90b27b","count":6,"msg":"no instance started yet, keep polling","time":"2015-05-14T16:07:30.337Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"fix system: 62999e58-66a0-4e50-a870-f2673acf6c79","time":"2015-05-14T16:07:33.069Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"user":{"name":"nscale aws autoscaling","email":"info@nearform.com"},"systemId":"62999e58-66a0-4e50-a870-f2673acf6c79","revisionId":"4b496e95e3b402552c9797c11c124d849901adcb","target":"autoscaling","mode":"live","out":{},"msg":"starting new deploy","time":"2015-05-14T16:07:33.070Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"system":"62999e58-66a0-4e50-a870-f2673acf6c79","msg":"analyze system","time":"2015-05-14T16:07:33.070Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"systemId":"62999e58-66a0-4e50-a870-f2673acf6c79","target":"autoscaling","msg":"get deployed system","time":"2015-05-14T16:07:33.191Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"running analysis against deployed system","time":"2015-05-14T16:07:33.192Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-46","pid":20212,"level":30,"msg":"fix system: sudc-system","time":"2015-05-14T16:07:33.415Z","v":0}

/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
TypeError: Cannot read property 'contains' of undefined
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/lib/postProcessing.js:71:58
    at Function.forEach (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/lodash/dist/lodash.js:3298:15)
    at handleAutoScalingGroups (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/lib/postProcessing.js:67:7)
    at postProcessing (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/lib/postProcessing.js:174:5)
    at onNext (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/index.js:51:7)
    at iterate (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/async/lib/async.js:149:13)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/async/lib/async.js:160:25
    at stripExtraneous (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/lib/stripExtraneous.js:28:3)
    at onNext (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nscale-aws-analyzer/index.js:51:7)
    at iterate (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/async/lib/async.js:149:13)
```

**Comment by mcollina** [comment]
I tried to reproduce the crash with nScale 0.16.1, and I was not able to. Can you please try again?

Here is what's happening:

1. when you stopped bombing the system, some AWS autoscaling events where generated
2. when nScale detects these events, it does a `system fix`, so it deploys automatically the containers
3. if you run a stop command during the `system fix` probably some bad things will happen

Note that all AWS instances are _never removed_, for safety.
